site_name: test
site_url: https://github.com/hankfwilson/test/
repo_url: https://github.com/hankfwilson/test/
edit_uri: ""
docs_dir: docs
theme: readthedocs
nav:
    - Home: index.md
    - About: about.md
