site_name: roastercoffees
site_url: https://github.com/hankfwilson/roastercoffees
repo_url: https://github.com/hankfwilson/roastercoffees
edit_uri: ""
docs_dir: docs
theme: readthedocs
nav:
    - Home: index.md
